sonar.projectKey=barbaratestingcompany_ProjetoAutomacaoJavaScriptPlaywright
sonar.organization=barbaratestingcompany
sonar.projectName=Projeto Automacao JavaScript Playwright
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.coverage.exclusions=**